// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using reminder_schedule_backend.Data;

#nullable disable

namespace reminder_schedule_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314060729_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("reminder_schedule_backend.Models.Admin", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("reminder_schedule_backend.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Classses");
                });

            modelBuilder.Entity("reminder_schedule_backend.Models.Schedule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("classId")
                        .HasColumnType("integer");

                    b.Property<int>("day")
                        .HasColumnType("integer");

                    b.Property<int>("sessionId")
                        .HasColumnType("integer");

                    b.Property<int>("subjectId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("classId");

                    b.HasIndex("sessionId");

                    b.HasIndex("subjectId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("reminder_schedule_backend.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("endime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("startime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("reminder_schedule_backend.Models.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("classId")
                        .HasColumnType("integer");

                    b.Property<string>("nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("nis")
                        .HasColumnType("integer");

                    b.Property<DateTime>("tanggalLahir")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("classId");

                    b.HasIndex("nis")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("reminder_schedule_backend.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("reminder_schedule_backend.Models.Teacher", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("passwordHash")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("reminder_schedule_backend.Models.Class", b =>
                {
                    b.HasOne("reminder_schedule_backend.Models.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("reminder_schedule_backend.Models.Schedule", b =>
                {
                    b.HasOne("reminder_schedule_backend.Models.Class", "Class")
                        .WithMany("schedules")
                        .HasForeignKey("classId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("reminder_schedule_backend.Models.Session", "session")
                        .WithMany()
                        .HasForeignKey("sessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("reminder_schedule_backend.Models.Subject", "subject")
                        .WithMany()
                        .HasForeignKey("subjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("session");

                    b.Navigation("subject");
                });

            modelBuilder.Entity("reminder_schedule_backend.Models.Student", b =>
                {
                    b.HasOne("reminder_schedule_backend.Models.Class", "Class")
                        .WithMany("students")
                        .HasForeignKey("classId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Class");
                });

            modelBuilder.Entity("reminder_schedule_backend.Models.Class", b =>
                {
                    b.Navigation("schedules");

                    b.Navigation("students");
                });

            modelBuilder.Entity("reminder_schedule_backend.Models.Teacher", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
